# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - livelines

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://potterjam.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6f9f3b9359534b1aab3a3364b8c50d89 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9947181f8ec54c0daf7766a752f9c399 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: potterjam.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6f9f3b9359534b1aab3a3364b8c50d89 }}/potterjam/livelines:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: 'https://livelin.es'

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'livelines'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c7f361641a584fbca5793418170daf19 }}
        images: 'potterjam.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6f9f3b9359534b1aab3a3364b8c50d89 }}/potterjam/livelines:${{ github.sha }}'